### ISSUE TITLE
Christmas Day Chart

### ISSUE THREAD

**Issue by mila-proenviro** [Pro-Enviro/IDNI#103]
Christmas Day Chart has data only for year 2023, but it is showing years 2022 and 2021. 
<img width="1631" alt="Screenshot 2024-05-30 at 14 15 09 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/ece03f3f-c2fd-4ad6-b37f-0f5d17779167">

**Comment by adamshelley31** [comment]
Can you test it works correctly? 
Even if you add new mpan etc

**Comment by mila-proenviro** [comment]
Tested on branch: "103-christmas-day-chart" and it is working
