### ISSUE TITLE
Nersi's requests

### ISSUE THREAD

**Issue by adamshelley31** [Pro-Enviro/IDNI#114]
~~1. Recommendations Table, add export button for Excel~~
~~2. Data Analysis table added with export function~~
3. Cost of energy -> Calculate CO2e if KWH selected (total units * conv factor)/1000
4. Co2e data from into 2 charts under PET Tool

**Comment by mila-proenviro** [comment]
1. Recommendations Table have export button and it is exporting excel file showing the totals as well.

**Comment by mila-proenviro** [comment]
4. Two pie charts were added to Pet Tool - branch name is "co2e-charts-pet-tool"
