### ISSUE TITLE
Maximum Demand Chart - ASC line

### ISSUE THREAD

**Issue by mila-proenviro** [Pro-Enviro/IDNI#118]
The ASC line is showing on charts that don't have asc information.
<img width="1551" alt="Screenshot 2024-06-12 at 13 00 41 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/734a0066-fefd-4140-921d-da6078022308">
<img width="772" alt="Screenshot 2024-06-12 at 13 00 49 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/f4dd1571-7a92-42bf-af9d-f09e91cd2591">

**Comment by mila-proenviro** [comment]
The issue is fix, but there is another issue.
When I added another ASC data for the second MPAN, the end date is not matching the end date that I selected.

**Comment by adamshelley31** [comment]
Can you test again @mila-proenviro - Does this work how it should?
