### ISSUE TITLE
Pet Tool - Pie chart - Breakdown

### ISSUE THREAD

**Issue by mila-proenviro** [Pro-Enviro/IDNI#120]
1. On pie chart there is some random fuel showing on the legend

<img width="789" alt="Screenshot 2024-06-12 at 15 45 50 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/d0227276-21e1-404a-9714-e68569ddb321">

2. When opening the page I need to save again the table so I can see the pie charts
3. Cost of Energy - after fill all the rows, the cost is not being calculated :
<img width="755" alt="Screenshot 2024-06-12 at 15 49 40 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/ab05a7df-07e7-42ec-9b2a-f33a24b03e2f">

**Comment by adamshelley31** [comment]
Ready for testing

**Comment by mila-proenviro** [comment]
Issues were fixed the only issue I found was "Annual Output (total units sold)" dropdown - liters is duplicating
<img width="777" alt="Screenshot 2024-06-13 at 10 42 44 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/7785af87-e21d-480c-917f-19dfa07a62f9">

**Comment by adamshelley31** [comment]
@mila-proenviro - Ready for you again to test.

**Comment by mila-proenviro** [comment]
issue was resolved on branch "co2e-charts-pet-tool" and was merged on main
