### ISSUE TITLE
Add Co2E table

### ISSUE THREAD

**Issue by adamshelley31** [Pro-Enviro/IDNI#127]
<img width="584" alt="Screenshot 2024-06-14 at 13 54 12" src="https://github.com/Pro-Enviro/IDNI/assets/148070121/de368e00-2316-4003-9078-d8ed15510c76">

**Comment by adamshelley31** [comment]
Adding to Branch #128

**Comment by adamshelley31** [comment]
Also need to test the Breakdown of Energy costs again. I added Electricity from HH data import

**Comment by mila-proenviro** [comment]
tested on branch "128" and if the "Consumption" is 0, this is breaking the table.

**Comment by adamshelley31** [comment]
Will need to check this is still happening on master branch. (I merged #128)
@mila-proenviro

**Comment by mila-proenviro** [comment]
I changed the fuel type name from "Electricity" to "New Type" and the numbers changed to 0.

<img width="1507" alt="Screenshot 2024-07-01 at 09 14 48" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/307b75c2-b2d8-403e-a153-d51ec3b9f123">

**Comment by mila-proenviro** [comment]
The gas is showing as 0, but I dont know why.
