### ISSUE TITLE
Fetching HH Costing from PET tool

### ISSUE THREAD

**Issue by adamshelley31** [Pro-Enviro/IDNI#174]
PET tool will have saved costing.
If users have saved their costing in the table for HH data. Attempt fetching from PET data to the Digital Twin Report.

**Comment by adamshelley31** [comment]
Costing added to the PET should now be shown in the digital-twin-report page. 

It will take the highest number it finds from from either the non-hh data or the PET tool. 
IF its electricity HH it will add onto the total.

Note: this branch is different to the one tested before. It will not prefill the PET page. This pulls from PET -> Digital-Twin-Report page.

**Comment by mila-proenviro** [comment]
So, I added PET Data on Capital Dev which is part of "New Cluster", and the number that I typed changed the numbers under digital twin report. Is that what we want this branch to do, I am not sure if I understand you right.
So far the pet data is showing under the digital twin report

<img width="1260" alt="Screenshot 2024-11-01 at 11 26 54" src="https://github.com/user-attachments/assets/7cce6974-48e1-46fc-ba0f-4500c3911e80">

<img width="1524" alt="Screenshot 2024-11-01 at 11 27 07" src="https://github.com/user-attachments/assets/518e82fd-41f1-41b9-9016-829b46b56571">
