### ISSUE TITLE
Digital Twin improvements

### ISSUE THREAD

**Issue by adamshelley31** [Pro-Enviro/IDNI#185]
Fix any digital twin bugs.
Lock it down to just Pro Enviro (Admins)

**Comment by mila-proenviro** [comment]
1.  After creating new cluster with companies, I click saved and the p-message showed 3 times 
<img width="1901" alt="Screenshot 2024-12-02 at 13 02 33" src="https://github.com/user-attachments/assets/9d0737f2-8cf8-469c-ab25-eea06a2e8c5f">

2. I managed to save the cluster after I clicked 2 times, on the first click nothing happend.
3. I noticed that this cluster is repeating twice, the first cluster is empty, the second cluster has companies attached to it.
<img width="760" alt="Screenshot 2024-12-02 at 13 09 12" src="https://github.com/user-attachments/assets/9fbdd587-a2d6-4972-88c0-931598959ad3">

4. I managed to create the same clutser but I used lower case
<img width="760" alt="Screenshot 2024-12-02 at 13 12 27" src="https://github.com/user-attachments/assets/cefcc9af-bc21-466c-8173-aa84dc5a0cd1">

5. I navigated to "digital-twin-report" page so I can check my cluster. My companies are appearing under the second "cool cluster" that I created and my first cluster is empty.

<img width="1546" alt="Screenshot 2024-12-02 at 13 16 49" src="https://github.com/user-attachments/assets/b1a0bf05-e7e6-48b5-af78-1cdc0343d22b">

<img width="1546" alt="Screenshot 2024-12-02 at 13 17 04" src="https://github.com/user-attachments/assets/b1ad1d09-7755-422a-8917-148189fc659c">

**Comment by adamshelley31** [comment]
1) Removed excess messaging on save.
2) **WIP**
3) That cluster duplicate is from a while ago, probably can delete one later
4) Added a check to prevent creation if its just lower case of an existing cluster
5) Think its okay as is, if companies can only ever be in one cluster I think thats what we want. 

Thank you for testing.

**Comment by mila-proenviro** [comment]
1. the p-message appears at the bottom 
<img width="1802" alt="Screenshot 2024-12-03 at 09 53 01" src="https://github.com/user-attachments/assets/f1ff6fe3-70ba-4d53-ac69-ecde68fda5c3">
2. I wasn't able to create the same cluster, when I used lower case, the only issue is that the p-message is appearing at the bottom of the page
<img width="1802" alt="Screenshot 2024-12-03 at 09 55 31" src="https://github.com/user-attachments/assets/9e168dbd-90fd-40c7-bdd0-0a98366053a5">
3. I created new cluster and when I clicked "Save" I can see this on the cosole: and I think you fix the issue
<img width="1674" alt="Screenshot 2024-12-03 at 09 58 23" src="https://github.com/user-attachments/assets/e0207bf7-7241-457e-97ec-b24a418e2960">
