### ISSUE TITLE
Bugs from Testing (19/04/24)

### ISSUE THREAD

**Issue by adamshelley31** [Pro-Enviro/IDNI#64]
LOGIN page
- Register Now button not working (Works on Angular version, not modx | Change link to /sign-up instead of /registration).
- Forgot Password button doesn’t do anything
- ~~No warning if user failed a sign in~~ *

Sign Up page
- ~~Register Needs to clear LocalStorage (Fixed with next Pull request)~~ * (Fixed in branch: #63)

Dashboard
- ~~Chart Download button not working (Working but the download btn has to be moved)~~ *
- ~~Electricity Consumption - tooltip not formatted correctly?~~ *

Fuel Data
- ~~Downloading fuel data spreadsheet - undefined name~~ * (Fixed in branch: #63)
- ~~- The unit column is not set by default. You have to select the unit manually.~~   (Fixed in branch: #63)

Data Upload
- ~~MPAN null error when uploading (Applies to Admin users)~~ *
- Emailer not working - CORS error on post
- ~~After the data is upload the page doesn't clear itself~~ *

Recommendation
- ~~Save button not there - This works in Angular version, not the Modx version~~ - mila fixed in modx *

Envirotracks
- Heatmap - mpan number disappearing after it was disselected and selected again
- ~~Heatmap Detailed - not showing, the chart is empty~~ *
- ~~Bar chart and Pie chart -  image files have the same name when we download them~~ *
- ~~Christmas Chart - the chart is missing, there is data for Christmas day, available under company "User Test 123"~~
- ~~Max Demand Chart - ASC not needed~~
- ~~Breakdown of CO2e by emissions source - not displaying even if there is a fuel data~~ *
- ~~Breakdown of CO2e by scope - when you download the img it is downloading svg instead of png, or that's how it should be ?~~ *

**Comment by adamshelley31** [comment]
Also Test logging in with microsoft edge - should prevent and warn the user to use another browser

**Comment by mila-proenviro** [comment]
tested the log in page on Micrsoft edge and a message appears : 'Please use another browser. Micrsoft edge is not supported'. It is working !

**Comment by mila-proenviro** [comment]
Fuel Data - The unit column is not set by default. You have to select the unit manually. - tested and not working
