### ISSUE TITLE
2nd level of access - Consultant

### ISSUE THREAD

**Issue by adamshelley31** [Pro-Enviro/IDNI#79]
Second level of access will allow people to be added to multiple companies.

Relational Users <-> Companies

**Comment by adamshelley31** [comment]
Worked on in #78

**Comment by mila-proenviro** [comment]
Bugs when Consultant is logged in:
1. When filling the recommendation table and saving it, the consultant is logged out. (error 403)
2. When the consultant is adding fuel data and saving it, the consultant is logged out. (error 403)

**Comment by adamshelley31** [comment]
@mila-proenviro - Can you test if its working now? I updated the consultant roles in Directus

**Comment by adamshelley31** [comment]
Merged with Dashboard-Upload
