### ISSUE TITLE
Christmas Chart Displaying to all companies

### ISSUE THREAD

**Issue by mila-proenviro** [Pro-Enviro/IDNI#81]
1. Christmas chart is displaying to all companies, including the ones that don't have data for Christmas day.

<img width="1872" alt="Screenshot 2024-05-16 at 10 13 44 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/567b0be1-8c19-4ccb-81fe-2461d8fc27ca">

**Comment by adamshelley31** [comment]
To be tested:
#quick-fixes-14-05 

1) Should reset the chart when changing company.
2) On initial load, the chart axis should not duplicate.

**Comment by mila-proenviro** [comment]
Tested on branch "quick-fixes" and it is working.
