### ISSUE TITLE
User Level - Display Company Name

### ISSUE THREAD

**Issue by mila-proenviro** [Pro-Enviro/IDNI#83]
Users are being able to see the company name in the panel. 

issue fixed on branch "user-selected-company"

**Comment by mila-proenviro** [comment]
@adamshelley31 please test

**Comment by adamshelley31** [comment]
Working ✅

Notes: 
1) You perhaps did this in your other branch, but standardise the font size for the text "Selected Company" if using. e.g. recommendations page looks different to others.
