### ISSUE TITLE
 Forgot Password

### ISSUE THREAD

**Issue by mila-proenviro** [Pro-Enviro/IDNI#92]
Forgot Password button doesn’t do anything

**Comment by adamshelley31** [comment]
You can also start testing this. 
It still is WIP. Forgot-password and reset-password pages need styles.
Email template also could use better styling too.

**Comment by mila-proenviro** [comment]
Tested on branch : "92-forgot-password", and forgotten password & reset password component were styled. Email templated was styled as well.
