### ISSUE TITLE
Mila to test 

### ISSUE THREAD

**Issue by adamshelley31** [Pro-Enviro/IDNI#98]
**PET Tool**
1) Added more steel types in material
2) Moved staff commute into company travel section, added an extra button there (one for company travel, one for staff commute)
3) Allowing users to change material types to custom ones if they wish by typing

**ASC**
Added ASC input below Data import
ASC should now show on demand chart correctly

**Comment by mila-proenviro** [comment]
Bug 1: 
Pet tool - Cost of energy - when typing a number to "Cost" column the number is coming as n/a 
<img width="841" alt="Screenshot 2024-05-29 at 10 22 05 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/daff8aa6-988c-4422-93f8-c9a475dd86dd">

**Comment by mila-proenviro** [comment]
ASC line is working

**Comment by mila-proenviro** [comment]
Cost of Raw Materials - after saving, the "General Material" names that I typed disappeared. But the type name is saved on the databse, it's just not visible.

<img width="813" alt="Screenshot 2024-05-29 at 12 39 58 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/3ac072af-bb99-4697-92a7-864079de229b">

**Comment by mila-proenviro** [comment]
New Bug Found:
1. Pet Tool - Cost of Row Materials - when click on "specific material" and "format" the dropdowns are not opening and I am getting a console log error - "ERROR TypeError: option is undefined".
The dropdown is not showing, but I can type my "specific material" & format.
<img width="1869" alt="Screenshot 2024-05-30 at 09 05 29" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/9230ee76-2d03-49f2-90d3-55c8165e4da5">
<img width="799" alt="Screenshot 2024-05-30 at 09 05 29 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/b68fa329-087a-47c6-84aa-53e02c5392a4">

2. Pet tool - Other Freight - approx mileage - when i deleted the number so I can type new one I get "N/A" on my input field.
<img width="763" alt="Screenshot 2024-05-30 at 09 18 11 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/1e658d2b-91cb-4e20-9d6e-fcae1311ca7a">

3.Pet Tool - Company Travel - Company travel row, when I typed my appox mileage my number showed as "N/A". 

<img width="779" alt="Screenshot 2024-05-30 at 09 21 06 (2)" src="https://github.com/Pro-Enviro/IDNI/assets/144015071/1bfbef2b-6e4c-4776-8c5a-48574d58f375">

**Comment by mila-proenviro** [comment]
tested on branch: "pet-upgrades" and it is working all issues were fixed
